
  pi_digits = "LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISCING ELIT SED"\
              "DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA"\
              "ALIQUA UT ENIM AD MINIM VENIAM QUIS NOSTRUD EXERCITATION"\
              "ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMMODO CONSEQUAT DUIS"\
              "AUTE IRURE DOLOR IN REPREHENDERIT IN VOLUPTATE VELIT ESSE"\
              "CILLUM DOLORE EU FUGIAT NULLA PARIATUR ENIM ANIMA EX ET AUTE"\
              "ANIMA ET IN ET DUIS UT EA DOLOR ESSE EU CILLUM EX IN DO UT"\
              "ALIQUA ANIMA PARIATUR ANIMA IRURE UT ENIM IPSUM EX ET ANIMA"\
              "IRURE ET IRURE AUTE ANIMA DOLOR ANIMA EA SIT EU ET LOREM"\
              "ANIMA EA MAGNA EA UT EX COMMODO ET MINIM NISI DOLOR NOSTRUD"\
              "MAGNA LABORE DOLORE ANIMA UT SED LABORE UT ENIM NULLA EU"\
              "ANIMA ET CILLUM IN EU IN ESSE ANIMA ESSE UT LOREM EX ANIMA"\
              "EU ANIMA UT MINIM SIT MINIM ANIMA IN ENIM ET ANIMA UT EX"\
              "IRURE EIUSMOD ALIQUIP MINIM NULLA LOREM ALIQUA NISI LABORE"\
              "MAGNA TEMPOR ANIMA EX ANIMA ULLAMCO IN DOLOR ANIMA"\
              "EXERCITATION EX SED MAGNA NULLA ESSE IN AUTE ANIMA EX VENIAM"\
              "EU ET EU DUIS QUIS ENIM IN ENIM ET EX QUIS VELIT IN ALIQUA"\
              "ESSE IN FUGIAT IN EU ULLAMCO FUGIAT VENIAM IRURE MINIM DO"\
              "AUTE EU LOREM AUTE ET DOLOR EX UT VELIT AUTE LABORIS ET EX"\
              "IN DOLORE ELIT UT IN CILLUM NISI ANIMA MAGNA ESSE UT CILLUM"\
              "DO IRURE ALIQUA VOLUPTATE EA QUIS ESSE ELIT NISI AMET EU"\
              "DOLORE AMET ET EU SIT ANIMA LABORIS VELIT FUGIAT UT DO EU"\
              "VELIT FUGIAT"/
def find
  if

  end
end